#pragma config(Sensor, S1,     LightSensor,    sensorLightActive)
#pragma config(Sensor, S2,     BumpSensor,     sensorTouch)
#pragma config(Sensor, S3,     DistanceSensor, sensorSONAR)
#pragma config(Motor,  motorA,          Middle,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          Right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          Left,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "robot.h"


task main()
{
	//wait1Msec(200); //wait 5 seconds
	float ratio = startState();
	mainloop(ratio);
	//
	//trunState();
	//runState();
}

void mainloop(float startRatio)
{
	float pastRatio = startRatio;
	const float changeValue = 0.0001;
	const float otherChange = 0.00005;
	float actualChange;
	bool finished = false;
	while(!finished) {
		colour c = getCurrentColour();
		int dir = 0;
		if(c == white)
		{
			dir = 1;
			actualChange = otherChange;
		}
		else if(c == off)
		{
			dir = -1;
			actualChange = changeValue;
		}

		float currentRatio = pastRatio + (changeValue*dir);
		if(currentRatio < -1)
			currentRatio = -1;
		if(currentRatio > 1)
			currentRatio = 1;
		moveRatio(currentRatio);
		pastRatio = currentRatio;
		displayInfo(currentRatio);
	}
}

void moveRatio(float ratio)
{
	int base = -10;
	int change = 5;
	int left = base - (ratio*change);
	int right = base + (ratio*change);
	move(left,right);
}

float startState()
{
	bool finished = false;
	float ratio = 0;

	while(!finished)
	{
		moveRatio(ratio);
		if (getCurrentColour() == black)
		{
			finished = true;
		}
		ratio -= 0.001;
		if(ratio < -0.8)
			ratio = -0.8;
		displayInfo(ratio);
	}
	return ratio;
}
void turnState()
{
	nMotorEncoder[Left]=0;
	nMotorEncoder[Right]=0;

	//while
}
void runState()
{
}

void move(int leftVal, int rightVal)
{
	motor[Left]=leftVal;
	motor[Right]=rightVal;
}

colour getCurrentColour()
{
	if(SensorValue[LightSensor] > whiteThreshold)
		return white;
	else if(SensorValue[LightSensor] < offThreshold)
		return off;
	return black;
}

void displayInfo(float ratio)
{
	nxtDisplayCenteredTextLine(0,"LMo %d",motor[Left]);
	nxtDisplayCenteredTextLine(1,"RMo %d",motor[Right]);
	nxtDisplayCenteredTextLine(2,"Sens %d",SensorValue[LightSensor]);
	nxtDisplayCenteredTextLine(3,"turn %f",ratio);
}
